### ISSUE TITLE
Wrong validation message

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloprp#68]
When creating an invoice with items, no invoice number was filled and no Distributor was selected. 
When we try to save the invoice, the below message is displayed:
![image](https://user-images.githubusercontent.com/26011197/27393022-8ac39bf8-567e-11e7-8cc6-5db208816581.png)

**Comment by tibeal** [comment]
**Note**: When Invoice Number and Distributor are blank, no validation should be done.

**Comment by tibeal** [comment]
Fixed in CI
