### ISSUE TITLE
Cannot create an invoice with (Invoice Number + Distributor) when this combination already exists for another program

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloprp#85]
Steps to reproduce:
- In Program A, create an invoice having Invoice Number and Distributor
- Approve this invoice
- In Program B, try to create another invoice with the same Invoice Number and the same Distributor used in the invoice of Program A.
The system doesn't allow the creation of the invoice and shows the message:  Duplicated Invoice Number for this Distributor
Should it be possible to create the same combinantion of Invoice Number + Distributor for different programs?

**Comment by tibeal** [comment]
Fixed in **CI**
