### ISSUE TITLE
Product Total Value - For some quantities x unit prices the total value is incorrectly calculated

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloprp#88]
In the example below, we have the same unit price being multiplied by different quantities.
For some reason, sometimes the total value shows extra decimal places.
![image](https://user-images.githubusercontent.com/26011197/29568105-addb2c5a-8725-11e7-8a93-e6c5d1aff7e0.png)

**Comment by tibeal** [comment]
Fixed in the CI

**Comment by mfernandagf** [comment]
The fix has generated a bug in "Amount".
![image](https://user-images.githubusercontent.com/26011197/30081102-4522956c-925c-11e7-9800-7fe2230c39fd.png)

**Comment by tibeal** [comment]
Fixed in CI
