### ISSUE TITLE
Invoice is being approved even if it has no product items

### ISSUE THREAD

**Issue by mfernandagf** [Fielo-Apps/fieloprp#97]
The program has the "Request Invoice Products" field set to true.
At CMS, the Invoice Upload page was configured to not show product items ("Has details" field set to false).
The member is able to submit the invoice without items in order to have the administrator completing the invoice items info. But if the administrator does not create any product item and presses the button "Close", the invoice has its status changed to "Approved".

**Comment by tibeal** [comment]
Fixed in CI.
